repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [--select, I, --fix]
      exclude: ^notebooks/.*
    # Run the formatter.
    - id: ruff-format
      exclude: ^notebooks/.*
